### ISSUE TITLE
Conda installation error

### ISSUE THREAD

**Issue by Samarth-T-Setty** [moiexpositoalonsolab/grenepipe#24]
(snakemake) samarth@ip-172-31-3-217:~/grenepipe$ mamba env create -f envs/grenepipe.yaml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 89, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/home/samarth/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 28, column 66:
         ... le" content="{&quot;groups&quot;: [], &quot;environmentKey&quot; ... 
                                             ^ (line: 28)

`$ /home/samarth/miniconda3/condabin/mamba create -f envs/grenepipe.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=snakemake
                CONDA_EXE=/home/samarth/miniconda3/bin/conda
             CONDA_PREFIX=/home/samarth/miniconda3/envs/snakemake
           CONDA_PREFIX_1=/home/samarth/miniconda3
    CONDA_PROMPT_MODIFIER=(snakemake)
         CONDA_PYTHON_EXE=/home/samarth/miniconda3/bin/python
               CONDA_ROOT=/home/samarth/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/samarth/miniconda3/envs/snakemake/bin:/home/samarth/miniconda3/c
                          ondabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
                          usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : snakemake
    active env location : /home/samarth/miniconda3/envs/snakemake
            shell level : 2
       user config file : /home/samarth/.condarc
 populated config files : 
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/samarth/miniconda3  (writable)
      conda av data dir : /home/samarth/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/samarth/miniconda3/pkgs
                          /home/samarth/.conda/pkgs
       envs directories : /home/samarth/miniconda3/envs
                          /home/samarth/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.28.1 CPython/3.9.12 Linux/5.15.0-1011-aws ubuntu/22.04 glibc/2.35
                UID:GID : 1003:1003
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by Samarth-T-Setty** [comment]
Hi All, I tried to install grenepipe on my AWS conda environment but it shows an error that I have pasted above. Could you please help?

**Comment by lczech** [comment]
Hi @Samarth-T-Setty,

that error seems to come from some mis-configured AWS conda setup file. The error is for example described [here](https://stackoverflow.com/q/60347063/4184258), so it's coming from a yaml file that is not correct - but not from the yaml file that you are using to specify the conda environment (that is, it's not the `envs/grenepipe.yaml` file that is broken).

With some digging and google sleuth work, and looking at the exact line where that error occurs in your error report above:

```
     ... le" content="{&quot;groups&quot;: [], &quot;environmentKey&quot; ... 
                                         ^ (line: 28)
```

I find that google gives me some obscure match to a file, see [here](https://raw.githubusercontent.com/Luois45/DNSBlocklists/auto-update/Malicious.txt) (fittingly, that file is name `Malicious.txt`, but no worries, it's just a text file and doesn't do harm) that contains this bit of text. And that file is related to `amazonaws` (see the beginning of that file), so hence I believe that this error is not related to grenepipe at all, but is a problem with AWS.

I'd contact their support, and tell them that your command

    mamba env create -f envs/grenepipe.yaml

fails, and ask them to fix it. That should be a pretty straight forward conda/mamba environment installation, and that already failing means that something is wrong on their end. I hope they get this figured out :-)

Hope that helps, so long
Lucas

**Comment by Samarth-T-Setty** [comment]
Thanks @lczech, I managed to figure out that the ### envs/grenepipe.yaml was not downloaded fully and I could get it working after creating a new one. I have used the DNA-seq cookie cutter template before and currently I see that installing the conda environments for the tools (from the wrappers) takes a really long time. From the past 2 days I have just been waiting on  the following steps - 

Building DAG of jobs...
Creating conda environment https:/github.com/snakemake/snakemake-wrappers/raw/0.51.3/bio/samtools/faidx/environment.yaml...
Downloading and installing remote packages.
Environment for ../../../../tmp/tmptv6ah28_.yaml created (location: .snakemake/conda/cd6d13c632d04332f5d4a51c66280271)
Removing incomplete Conda environment ../envs/picard.yaml...
Creating conda environment ../envs/picard.yaml...
Downloading and installing remote packages.






Environment for ../envs/picard.yaml created (location: .snakemake/conda/3eeaf74a4852753209edc9a65d7e91a3)
Creating conda environment ../envs/bwa.yaml...
Downloading and installing remote packages.
Environment for ../envs/bwa.yaml created (location: .snakemake/conda/fb41ee5b51ce5a2d5decf9573b3a8e96)
Removing incomplete Conda environment ../envs/qualimap.yaml...
Creating conda environment ../envs/qualimap.yaml...
Downloading and installing remote packages.



Any way to speeden up the conda env. installs?

**Comment by Samarth-T-Setty** [comment]
Here are the versions - 
 Conda:              4.12.0
    Python:             3.7.10
    Snakemake:          6.0.5
    Grenepipe:          0.9.0
    Command:            /home/samarth/miniconda3/envs/grenepipe/bin/snakemake
                        --use-conda -j 25 -kp
                        --directory run

    Base directory:     /home/samarth/sample_run
    Working directory:  /home/samarth/sample_run/run
    Config file(s):     /home/samarth/sample_run/run/config.yaml
    Samples:            32

**Comment by lczech** [comment]
Yes, when running, also specify `--conda-frontend mamba`, that will speed things up massively! You'll need to have mamba installed for this, which conveniently can be done via conda with `conda install -c conda-forge mamba`. 

I have had similar experiences with conda being slow, also for the picard environment that you are seeing being slow there as well. It seems that conda is struggling with that... I'll keep it in mind and see if I can find a fix for that. But for now, just use mamba ;-)

**Comment by Samarth-T-Setty** [comment]
Thanks, mamba worked well for me and the pipeline is running smoothly so far.

**Comment by lczech** [comment]
Yeeey, happy to hear! I'll close this issue then, but feel free to start a new one should anything else not work :-)
