### ISSUE TITLE
restrict-regions and short contigs

### ISSUE THREAD

**Issue by RvV1979** [moiexpositoalonsolab/grenepipe#36]
Hi Lucas, 

I wish to call specific sites and have found that using the `restrict-regions` option to indicate a intervals.bed file specifying those sites works for this purpose (in combination with `HaplotypeCaller-extra: "--output-mode EMIT_ALL_CONFIDENT_SITES"`). 

However, my reference genome includes some very small contigs and in order to avoid overwhelmingly many jobs, I have previously been using the `contig-group-size` option. This is unfortunately not yet possible in combination with 'restrict-regions`.  

Is there a way to specify these sites without generating overwhelmingly many jobs? Perhaps by adding a single job making empty vcf files for contigs that do not occur in the intervals.bed file?

But of course, ensuring compatibility between both `contig-group-size` and `restrict-regions` would be ideal... 

Thanks

**Comment by RvV1979** [comment]
Just to update (for the benefit of others who may want to do something similar): 
As expected, the combination of both `contig-group-size` and `restrict-regions` resulted in a large number of jobs. However, the jobs for contigs without overlaps with the `intervals.bed` file  finished within seconds. In conclusion: spurious jobs and files but fortunately not too much increase in total computation time.

**Comment by lczech** [comment]
Dear @RvV1979,

indeed, that is a combination of features that is a bit tricky to implement, and I will unfortunately not have the time for that in the foreseeable future. Hope it's okay that I cannot promise a timeline on implementing this. 

Let's keep this issue open for now. And in the future, anyone else who wants to do something similar, please feel free to comment here to bump this up in priority in my implementation back log :-)

Also, thank you for reporting your experience with just running it as-is. That sounds like it's generally workable, with some overhead in terms of job submissions and files created. That is good to know!

All the best
Lucas

**Comment by meixilin** [comment]
Hi, 

I have an issue that might be relevant to this thread. I have noticed that when I set `contig-group-size: 0`, the pipeline runs fine (with a lot of jobs though given the amount of contigs). 

```
job                                      count
-------------------------------------  -------
all                                          1
all_bams                                     1
all_pileups                                  1
bam_index                                    1
call_variants                              280
combine_calls                              280
dedup_reports_collect                        1
gatk_hard_filter_calls                       2
genotype_variants                          280
merge_calls                                  1
merge_variants                               1
mpileup_all_samples                          1
multiqc                                      1
picard_collectmultiplemetrics                1
picard_collectmultiplemetrics_collect        1
qualimap_collect                             1
qualimap_sample                              1
samtools_flagstat                            1
samtools_flagstat_collect                    1
samtools_stats                               1
samtools_stats_collect                       1
select_calls                                 2
total                                      861
```

However, when I set a `contig-group-size: 34000000`, the `calling/contig-groups` folders get created just fine, but there are no more `call_variants` jobs created, in addition, the pipeline fails at the `bam_index`job this time.

```
job                                      count
-------------------------------------  -------
all                                          1
all_bams                                     1
all_pileups                                  1
contig_groups                                1
dedup_reports_collect                        1
fastqc                                       2
fastqc_collect                               1
gatk_hard_filter_calls                       2
map_reads                                    1
mark_duplicates                              1
merge_calls                                  1
merge_sample_unit_bams                       1
merge_variants                               1
mpileup_all_sample_names                     1
mpileup_all_samples                          1
multiqc                                      1
picard_collectmultiplemetrics                1
picard_collectmultiplemetrics_collect        1
qualimap_collect                             1
qualimap_sample                              1
samtools_flagstat                            1
samtools_flagstat_collect                    1
samtools_stats                               1
samtools_stats_collect                       1
select_calls                                 2
trim_reads_pe                                1
trimming_reports_collect                     1
trimmomatic_multiqc_log                      1
total                                       31
```

The error message is:  

```
Full Traceback (most recent call last):
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/workflow.py", line 1248, in execute
    raise e
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/workflow.py", line 1244, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/scheduler.py", line 198, in schedule
    self._finish_jobs()
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/scheduler.py", line 388, in _finish_jobs
    async_run(postprocess())
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/common/__init__.py", line 94, in async_run
    return asyncio.run(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "micromamba/envs/grenepipe/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "micromamba/envs/grenepipe/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "micromamba/envs/grenepipe/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/scheduler.py", line 383, in postprocess
    await self.workflow.dag.finish(
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/dag.py", line 1879, in finish
    potential_new_ready_jobs = self.update_ready(depending)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "micromamba/envs/grenepipe/lib/python3.12/site-packages/snakemake/dag.py", line 1578, in update_ready
    group = self._group[job]
            ~~~~~~~~~~~^^^^^
KeyError: bam_index
```

Any thoughts would be greatly appreciated!

**Comment by lczech** [comment]
Hi @meixilin,

moved this to https://github.com/moiexpositoalonsolab/grenepipe/issues/52, because this issue here is more about a question / feature request than a bug. Let's continue over there :-)

Cheers
Lucas
