### ISSUE TITLE
not sure what the issue is

### ISSUE THREAD

**Issue by Leovar101** [moiexpositoalonsolab/grenepipe#49]
Hei it's Yannick again. 
As recommended, I started from stratch with the new release and installed micromamba and the newest version of snakemake alongside it.
When trying to do a test run, I immediately am greeted by this:

Building DAG of jobs...
/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/dag.py:1612: RuntimeWarning: coroutine 'DAG.sanitize_local_storage_copies' was never awaited
  self.sanitize_local_storage_copies()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/bin/bash: conda: command not found
Traceback (most recent call last):

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1122, in execute
    self.dag.create_conda_envs()

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/dag.py", line 452, in create_conda_envs
    env.create(self.workflow.dryrun)

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 392, in create
    pin_file = self.pin_file
               ^^^^^^^^^^^^^

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake_interface_common/utils.py", line 33, in __get__
    value = self.method(instance)
            ^^^^^^^^^^^^^^^^^^^^^

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 102, in pin_file
    f".{self.conda.platform}.pin.txt"
        ^^^^^^^^^^

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake_interface_common/utils.py", line 33, in __get__
    value = self.method(instance)
            ^^^^^^^^^^^^^^^^^^^^^

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 95, in conda
    return Conda(
           ^^^^^^

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 654, in __init__
    shell.check_output(self._get_cmd("conda info --json"), text=True)

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 64, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/gpfs/bwfor/home/fr/fr_fr/fr_yf1009/micromamba/envs/snakemake/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 127.

What exactly is happening here? I'll attach the logfile in case that helps. 
[2024-07-17T143629.772838.snakemake.log](https://github.com/user-attachments/files/16265773/2024-07-17T143629.772838.snakemake.log)

Sorry if this turns out to be a minor issue.
Best regards
Yannick

**Comment by lczech** [comment]
Hey Yannick,

so, you installed the grenepipe env via micromamba, then activated it, and then ran snakemake from within that environment? What are the exact commands that you are running there?

Lucas

**Comment by Leovar101** [comment]
Hei Lucas, 

I have to admit to my shame that in this instance, I forgot to activate the grenepipe environment after starting up the new tmux session. 
I'll see if I run into an issue this time, but I think it was just me being negligent.
Sorry for any wasted time!
Yannick

**Comment by lczech** [comment]
Okay, interesting, a lot is going on here... 

First, the error was in sample `B-1`, not `D-1`. Could you maybe also send me the file `logs/mapping/bwa-mem/B-1.log`?

Furthermore, the error message

```
PermissionError: [Errno 13] Permission denied: '/scratch/fr_yf1009_o05i14'
```

somehow indicates some issue with that directory. I assume that is some user scratch space or temporary directory? It could be that Snakemake automatically sets this, following some configuration of your cluster - not sure where that exact directory is coming from. But it could for instance be that there is no more space there, or some similar issue. Could you check that?

Furthermore, I am noticing the following warning of grenepipe in the beginning of your log file:

```
In the reference genome, there are chromosome/contig names that contain problematic characters. As we use these names to create file names, this can lead to crashes later in the pipeline. We generally advise to only use alpha-numeric characters, dots, dashes, and underscores for the reference sequence names for this reason.
Problematic reference genome names:
 - lcl|ptg000001l
 - lcl|ptg000002l
 - lcl|ptg000003l
 - ...
```

The issue here is that your reference genome contains pipe (or bar) characters `|`. This will very likely lead to issues down the line, as that is a special character in unix systems, and using it in file names can lead to all kind of trouble. Depending on your settings, grenepipe will however create files for the contigs, named after the contigs, so that might fail.

Hence, I highly recommend to rename the reference genome sequences, for instance by replacing the `|` with a simply underscore `_`. I have thought about doing that automatically in grenepipe, but concluded that it would probably be more trouble for the user to find all their contigs renamed after the fact. But let me know what you think about that.

Lastly, the log file you sent also made me realize that Snakemake changed their logging behaviour, so that the log file that you sent does not contain all information of grenepipe any more... I've [told them about it](https://github.com/snakemake/snakemake/issues/2974). In the meantime, for future debugging, when you need to send more log files, could you maybe use the latest `master` branch of the grenepipe repository, e.g., via the green "Code" button [here](https://github.com/moiexpositoalonsolab/grenepipe). That will produce an additional log file almost identical to the one you sent there, but with all the information. It will be located along the other logs of the pipeline in `logs/snakemake`.

Cheers and so long
Lucas

**Comment by Leovar101** [comment]
Hei Lucas,

unfortunately no log seems to have been created for `B-1`, I added the only one in the bwa-mem log folder.
Also, I'm not sure how to check this scratch directory. As far as I understand it's stored on our cluster's temporary file directory $TMPDIR, which appears to be emptied as soon as the corresponding jobs are either done or terminated. 
At least it seems to be empty now.
I've changed to contig names in the reference genome and replaced the grenepipe folder with your master version and am about to start a new run now.
I'll let you know what happens!

All the best
Yannick

**Comment by lczech** [comment]
Hej Yannick,

> unfortunately no log seems to have been created for B-1, I added the only one in the bwa-mem log folder.

Ah okay, that likely means the just failed for some snakemake reason, so that the program being run there did not even get to produce any output.

> Also, I'm not sure how to check this scratch directory. As far as I understand it's stored on our cluster's temporary file directory $TMPDIR, which appears to be emptied as soon as the corresponding jobs are either done or terminated.
edit: I managed to acces it, and du -sh for the directory returns a size of 8.0K

Haha yes, 8K is not nearly enough space... not sure why your cluster would give you such limited temp space... I'd get in touch with your admins to see what is happening there.

In the meantime, you can set the temp dir explicitly to something that has more space available, see [here](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#standard-resources). This should for example work:

    --default-resources tmpdir="/path/to/more/space"

> I've changed to contig names in the reference genome and replaced the grenepipe folder with your master version and am about to start a new run now.
I'll let you know what happens!

Great! 

So long
Lucas

**Comment by Leovar101** [comment]
Hei Lucas,

> Haha yes, 8K is not nearly enough space... not sure why your cluster would give you such limited temp space... I'd get in touch with your admins to see what is happening there.

I double-checked and as far as I can tell, there should be no quota and therefore unlimited space in the temp directories, so it is a bit of a mystery. I'll try your approach if/when the current analysis fails.

Cheers
Yannick

**Comment by lczech** [comment]
UNLIMITED SPACE? You could get rich! :-D

Yes, see what happens. If things get deleted from that temp dir once the job finishes, it could be that it is too eagerly deleting files before Snakemake is done moving them to the actual results dir, or something like that. 

Cheers
Lucas

**Comment by Leovar101** [comment]
Hi Lucas,

the last attempt unfortunately also finished with the same "permission denied" notification in regards to that scratch directory.
Here the snakemake log, I hope this one is the one you'd need:
[2024-07-18T111225.342551.snakemake.log](https://github.com/user-attachments/files/16310017/2024-07-18T111225.342551.snakemake.log)


Interestingly, the analysis got much further than the last time. 
Is there a way to have a new run start where this one left off? 

Cheers
Yannick

**Comment by lczech** [comment]
Hi Yannick,

> the last attempt unfortunately also finished with the same "permission denied" notification in regards to that scratch directory.

That does not look like an issue with Snakemake or grenepipe, but rather with your cluster configuration, so there is not much I can do to fix that particular error. If you want to keep using that scratch space, I'd get in touch with the cluster admin, to see what is causing this. 

In the meantime, you can instead instruct Snakemake to use a different directory for temp files, as [explained above](https://github.com/moiexpositoalonsolab/grenepipe/issues/49#issuecomment-2236133122). Have you tried that?

> Interestingly, the analysis got much further than the last time.

Hm not sure that I understand. Your previous run went from 15:10 to 18:07, and your new one from 11:12 to 17:16, which seems longer to me :-) 

> Is there a way to have a new run start where this one left off?

Yes, Snakemake usually does not run things that are already there and up to date. However, if an input file changes, any output files that depend on it will be re-created. That is determined via time stamps, so if the input is newer than the output, the job creating the output is executed again.

In your case it seems that the reference file was updated:

```
[Thu Jul 18 11:12:28 2024]
localcheckpoint samtools_faidx:
    input: /gpfs/bwfor/home/fr/fr_fr/fr_yf1009/GenoDat/Mbel_Q1_clean.fasta
    output: /gpfs/bwfor/home/fr/fr_fr/fr_yf1009/GenoDat/Mbel_Q1_clean.fasta.fai
    log: /gpfs/bwfor/home/fr/fr_fr/fr_yf1009/GenoDat/logs/Mbel_Q1_clean.fasta.samtools_faidx.log
    jobid: 7
    reason: Updated input files: /gpfs/bwfor/home/fr/fr_fr/fr_yf1009/GenoDat/Mbel_Q1_clean.fasta
    resources: tmpdir=/scratch/fr_yf1009_o05i14
DAG of jobs will be updated after completion.
```

Did you somehow change or move that file in the meantime? If so, that would explain the re-running.

So long
Lucas

**Comment by lczech** [comment]
Hi @Leovar101,

any updates on this?

Cheers
Lucas

**Comment by lczech** [comment]
Hi @Leovar101,

did you get things to work now? I'll close the issue for now, but feel free to comment or start a new one if you have any further trouble!

Cheers
Lucas

**Comment by Leovar101** [comment]
Hi Lucas, 

I'm so sorry, I had my notifications turned off during my holidays and forgot to ever come back to this after I resumed my work on the project. 
To make it short: 
it worked, I got my preliminary samples analysed without further hiccups. The issue seemed to be related to the requests made by slurm whenever I tried letting the analysis run in a tmux session, which then got not enough space allocated to operate. 
I resolved this issue by simply not using a multiplexer and keeping the terminal running on a spare desktop. So I'll probably resort to have this machine set up solely for lengthy analyses in the future and all should be fine!
Thank you so much for your continued help and interest, and again sorry it took me so long to reply!

Cheers 
Yannick

**Comment by lczech** [comment]
Hi Yannick,

oh wow, okay, glad you figured this out! Weird though that tmux is causing a memory issue there... it should not matter for Snakemake from where it's being run - that should not affect how much memory it needs to operate. Or does that spare desktop have more memory available? In that case, yes, that seems to be a workable solution (or rather, workaround...), but if that's the issue, there is unfortunately nothing else I can do from the point of view of grenepipe to help you.

Thanks for letting me know, and good luck with the further analyses! Also, of course, for any other issues that are indeed caused by grenepipe, just open a new issue here ;-)

Cheers
Lucas

**Comment by Leovar101** [comment]
Hi Lucas, 

I'm not exactly sure what the memory issue was or is. All I can say is that it persisted when multiplexing terminals with tmux and detaching from that session.  Re-attaching would show everything working normal for a couple of hours, but then the memory error would show up after a while. If I ran it on an open default terminal, then it all continued as expected. The machine I used for the terminal is just a cheap 10 year server desktop I had built once, so I suppose the memory of the machine is irrelevant, the session just had to be kept open for the entire time. I suppose the issue is due to how our server admin handles requests coming from a detached tmux session. 
But considering it all worked from a terminal that I just kept open until the whole process was done, there should be no issue with either snakemake or grenepipe itself.

Sure thing, I'm glad I made this github community experience ^^
Cheery
Yannick
